name: CI

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main
      - release/**

jobs:
  test:
    runs-on: codeberg-medium
    steps:
      - uses: actions/checkout@v6
